### ISSUE TITLE
Adjust angle

### ISSUE THREAD

**Issue by tomchiverton** [PuffyCoffee/3D-Pie-chart#3]
It would be nice to change the angle the pie is viewed at.

If I got my head around the math, this would be an easy patch for me to add. Any ideas what variable in the drawing code it is ?

**Comment by PuffyCoffee** [comment]
Added feature that allows user to adjust viewing angle.
```js
Raphael('canvas', 700, 500).pie({
	values: [87, 134, 83, 23, 98],
	colors: ["#00ff00", "#ff0011", "#faf600", "#0079fa", "#fa8500"],
	tooltip: ["January - 87", "Feburary - 136", "March - 77", "April - 120","May - 34"],
	doughnut: true,
	radius: 200,
	tilt: "l",
	chartTitle: "Monthly Payment",
	legend: {
		display: true,
		items: ["January - 87", "Feburary - 136", "March - 77", "April - 120","May - 34"]
	}
});
```
__tilt__ option was added, __"x", "l", "m" and "s"__ can be picked to adjust viewing angle of pie/doughnut charts.

* "x": Extra large angle
* "l": Large angle (default)
* "m": Medium angle
* "s": Small angle
